### PR TITLE
Created api for TestFramework and TestRunner

### PR DESCRIPTION
**Pull request by nicojs**
Created highlevel api for TestFramework and TestRunner. Should be moved to its own git repo, but leave in here for the time being.
Solve issue #27 

@simondel could you review it

### CODE REVIEW

**Comment by nicojs** [comment]
@simondel it now is an optional property, together with all other properties.

**Comment by simondel** [comment]
I have a question about the following interface:

```
interface TestRunResult {
  specNames: string[];
  succeeded?: number;
  failed?: number;
  timedOut?: number;
  errorOccurred?: number;
  timeSpent?: number;
  coverage?: CoverageResult;
}
```

Why is are `timedOut` and `errorOccurred` numbers? Right now these two properties are of type `boolean` in the file `src/TestResult.ts`.

**Comment by nicojs** [comment]
ah yes, that is indeed better, i will update the PR.

**Comment by nicojs** [comment]
I choose to do it with an enum, is this better?

**Comment by simondel** [comment]
LGTM!

**Pull request merged**
