### PR TITLE
Added new karma-test-runner

### PR DESCRIPTION
**Pull request by nicojs**
Added the new karma-test-runner which satisfies the api from #27 . 

1. Re-ordered the modular imports. The idea is that we have multiple named exports per sub-module, angular 2 style.
2. Altered the api: the run() method now returns a promise.
3. Altered the api: added additional options object for test runner instances specifics.
4. No support for timeout, see #30

### CODE REVIEW

**Comment by simondel** [comment]
I noticed that the Karma test runner is not `silent` when the tests are ran, while it is silent when stryker is being executed.

Is this a bug or are the tests no longer supposed to be `silent`?

**Comment by nicojs** [comment]
> I noticed that the Karma test runner is not silent when the tests are ran, 

That is correct. The karma test runner is not using a child process, and thus the output is visible when running unit tests.

It is not visible when Stryker is being executed, because Stryker isn't using the new test runner yet ;). For that to work, we also need the other components to work is specified by the new api, meaning the JasmineTestFramework #32 and the TestRunnerFasade #30

**Comment by nicojs** [comment]
I added some more commits, because i felled like the plugin model was part of this pull request. So the karma-runner now registers itself to the TestRunnerFactory (new class)

**Comment by simondel** [comment]
We'll have to add comments in the near future so our API is documented but for now we can do without it.

It looks good! Well done :)

**Comment by nicojs** [comment]
solved issue #25

**Pull request merged**
